package retail.modelo.entidades;
// Generated 02-18-2019 03:12:08 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Clientes generated by hbm2java
 */
public class Clientes  implements java.io.Serializable {


     private int idCliente;
     private String nombreCliente;
     private String apellidoCliente;
     private String direccionCliente;
     private String telefonoCliente;
     private char sexoCliente;
     private Set ventases = new HashSet(0);

    public Clientes() {
    }

	
    public Clientes(int idCliente, String nombreCliente, String apellidoCliente, String direccionCliente, String telefonoCliente, char sexoCliente) {
        this.idCliente = idCliente;
        this.nombreCliente = nombreCliente;
        this.apellidoCliente = apellidoCliente;
        this.direccionCliente = direccionCliente;
        this.telefonoCliente = telefonoCliente;
        this.sexoCliente = sexoCliente;
    }
    public Clientes(int idCliente, String nombreCliente, String apellidoCliente, String direccionCliente, String telefonoCliente, char sexoCliente, Set ventases) {
       this.idCliente = idCliente;
       this.nombreCliente = nombreCliente;
       this.apellidoCliente = apellidoCliente;
       this.direccionCliente = direccionCliente;
       this.telefonoCliente = telefonoCliente;
       this.sexoCliente = sexoCliente;
       this.ventases = ventases;
    }
   
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }
    public String getNombreCliente() {
        return this.nombreCliente;
    }
    
    public void setNombreCliente(String nombreCliente) {
        this.nombreCliente = nombreCliente;
    }
    public String getApellidoCliente() {
        return this.apellidoCliente;
    }
    
    public void setApellidoCliente(String apellidoCliente) {
        this.apellidoCliente = apellidoCliente;
    }
    public String getDireccionCliente() {
        return this.direccionCliente;
    }
    
    public void setDireccionCliente(String direccionCliente) {
        this.direccionCliente = direccionCliente;
    }
    public String getTelefonoCliente() {
        return this.telefonoCliente;
    }
    
    public void setTelefonoCliente(String telefonoCliente) {
        this.telefonoCliente = telefonoCliente;
    }
    public char getSexoCliente() {
        return this.sexoCliente;
    }
    
    public void setSexoCliente(char sexoCliente) {
        this.sexoCliente = sexoCliente;
    }
    public Set getVentases() {
        return this.ventases;
    }
    
    public void setVentases(Set ventases) {
        this.ventases = ventases;
    }




}


