package retail.modelo.entidades;
// Generated 02-18-2019 03:12:08 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Compra generated by hbm2java
 */
public class Compra  implements java.io.Serializable {


     private int idCompra;
     private Date fechaCompra;
     private Date fechaInventario;
     private Date fechaDocumento;
     private double totalCompra;
     private Provider proveedor;
     private int estado;
     private Set detallecompras = new HashSet(0);
     private String noDocumento;

    public Compra() {
    }

	
    public Compra(int idCompra, Date fechaCompra, double totalCompra, Provider proveedor, int estado) {
        this.idCompra = idCompra;
        this.fechaCompra = fechaCompra;
        this.totalCompra = totalCompra;
        this.proveedor = proveedor;
        this.estado = estado;
    }
    public Compra(int idCompra, Date fechaCompra, double totalCompra, Provider proveedor, int estado, Set detallecompras) {
       this.idCompra = idCompra;
       this.fechaCompra = fechaCompra;
       this.totalCompra = totalCompra;
       this.proveedor = proveedor;
       this.estado = estado;
       this.detallecompras = detallecompras;
    }
   
    public int getIdCompra() {
        return this.idCompra;
    }
    
    public void setIdCompra(int idCompra) {
        this.idCompra = idCompra;
    }
    public Date getFechaCompra() {
        return this.fechaCompra;
    }
    
    public void setFechaCompra(Date fechaCompra) {
        this.fechaCompra = fechaCompra;
    }
    public double getTotalCompra() {
        return this.totalCompra;
    }
    
    public void setTotalCompra(double totalCompra) {
        this.totalCompra = totalCompra;
    }
    public Provider getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Provider proveedor) {
        this.proveedor = proveedor;
    }
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }
    public Set getDetallecompras() {
        return this.detallecompras;
    }
    
    public void setDetallecompras(Set detallecompras) {
        this.detallecompras = detallecompras;
    }

    public Date getFechaInventario() {
        return fechaInventario;
    }

    public void setFechaInventario(Date fechaInventario) {
        this.fechaInventario = fechaInventario;
    }

    public Date getFechaDocumento() {
        return fechaDocumento;
    }

    public void setFechaDocumento(Date fechaDocumento) {
        this.fechaDocumento = fechaDocumento;
    }

    public String getNoDocumento() {
        return noDocumento;
    }

    public void setNoDocumento(String noDocumento) {
        this.noDocumento = noDocumento;
    }




}


