package retail.modelo.entidades;
// Generated 02-18-2019 03:12:08 PM by Hibernate Tools 4.3.1



/**
 * Detalleventa generated by hbm2java
 */
public class Detalleventa  implements java.io.Serializable {


     private int idDetalleVenta;
     private Producto producto;
     private Ventas ventas;
     private int cantidadDetalle;
     private double precioDetalle;
     private double totalDetalle;

    public Detalleventa() {
    }

    public Detalleventa(int idDetalleVenta, Producto producto, Ventas ventas, int cantidadDetalle, double precioDetalle, double totalDetalle) {
       this.idDetalleVenta = idDetalleVenta;
       this.producto = producto;
       this.ventas = ventas;
       this.cantidadDetalle = cantidadDetalle;
       this.precioDetalle = precioDetalle;
       this.totalDetalle = totalDetalle;
    }
   
    public int getIdDetalleVenta() {
        return this.idDetalleVenta;
    }
    
    public void setIdDetalleVenta(int idDetalleVenta) {
        this.idDetalleVenta = idDetalleVenta;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Ventas getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Ventas ventas) {
        this.ventas = ventas;
    }
    public int getCantidadDetalle() {
        return this.cantidadDetalle;
    }
    
    public void setCantidadDetalle(int cantidadDetalle) {
        this.cantidadDetalle = cantidadDetalle;
    }
    public double getPrecioDetalle() {
        return this.precioDetalle;
    }
    
    public void setPrecioDetalle(double precioDetalle) {
        this.precioDetalle = precioDetalle;
    }
    public double getTotalDetalle() {
        return this.totalDetalle;
    }
    
    public void setTotalDetalle(double totalDetalle) {
        this.totalDetalle = totalDetalle;
    }




}


