package retail.modelo.entidades;
// Generated 02-18-2019 03:12:08 PM by Hibernate Tools 4.3.1



/**
 * Detallecompra generated by hbm2java
 */
public class Detallecompra  implements java.io.Serializable {


     private int idDetalleCompra;
     private Compra compra;
     private Producto producto;
     private double precioDetalle;
     private double totalDetalle;
     private int cantidadDetalle;

    public Detallecompra() {
    }

    public Detallecompra(int idDetalleCompra, Compra compra, Producto producto, double precioDetalle, double totalDetalle, int cantidadDetalle) {
       this.idDetalleCompra = idDetalleCompra;
       this.compra = compra;
       this.producto = producto;
       this.precioDetalle = precioDetalle;
       this.totalDetalle = totalDetalle;
       this.cantidadDetalle = cantidadDetalle;
    }
   
    public int getIdDetalleCompra() {
        return this.idDetalleCompra;
    }
    
    public void setIdDetalleCompra(int idDetalleCompra) {
        this.idDetalleCompra = idDetalleCompra;
    }
    public Compra getCompra() {
        return this.compra;
    }
    
    public void setCompra(Compra compra) {
        this.compra = compra;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public double getPrecioDetalle() {
        return this.precioDetalle;
    }
    
    public void setPrecioDetalle(double precioDetalle) {
        this.precioDetalle = precioDetalle;
    }
    public double getTotalDetalle() {
        return this.totalDetalle;
    }
    
    public void setTotalDetalle(double totalDetalle) {
        this.totalDetalle = totalDetalle;
    }
    public int getCantidadDetalle() {
        return this.cantidadDetalle;
    }
    
    public void setCantidadDetalle(int cantidadDetalle) {
        this.cantidadDetalle = cantidadDetalle;
    }




}


