package retail.modelo.entidades;
// Generated 02-18-2019 03:12:08 PM by Hibernate Tools 4.3.1



/**
 * OrderDetailId generated by hbm2java
 */
public class OrderDetailId  implements java.io.Serializable {


     private int orderdetailid;
     private String orderid;

    public OrderDetailId() {
    }

    public OrderDetailId(int orderdetailid, String orderid) {
       this.orderdetailid = orderdetailid;
       this.orderid = orderid;
    }
   
    public int getOrderdetailid() {
        return this.orderdetailid;
    }
    
    public void setOrderdetailid(int orderdetailid) {
        this.orderdetailid = orderdetailid;
    }
    public String getOrderid() {
        return this.orderid;
    }
    
    public void setOrderid(String orderid) {
        this.orderid = orderid;
    }




}


