package retail.modelo.entidades;
// Generated 02-18-2019 03:12:08 PM by Hibernate Tools 4.3.1



/**
 * OrderDetail generated by hbm2java
 */
public class OrderDetail  implements java.io.Serializable {


     private OrderDetailId id;
     private OrderMaster orderMaster;
     private Producto product;
     private Float orderdetailquantity;
     private Float orderdetailtotal;
     private Float orderdetailunitprice;
     private String productcolor;

    public OrderDetail() {
    }

	
    public OrderDetail(OrderDetailId id, OrderMaster orderMaster) {
        this.id = id;
        this.orderMaster = orderMaster;
    }
    public OrderDetail(OrderDetailId id, OrderMaster orderMaster, Producto product, Float orderdetailquantity, Float orderdetailtotal, Float orderdetailunitprice, String productcolor) {
       this.id = id;
       this.orderMaster = orderMaster;
       this.product = product;
       this.orderdetailquantity = orderdetailquantity;
       this.orderdetailtotal = orderdetailtotal;
       this.orderdetailunitprice = orderdetailunitprice;
       this.productcolor = productcolor;
    }
   
    public OrderDetailId getId() {
        return this.id;
    }
    
    public void setId(OrderDetailId id) {
        this.id = id;
    }
    public OrderMaster getOrderMaster() {
        return this.orderMaster;
    }
    
    public void setOrderMaster(OrderMaster orderMaster) {
        this.orderMaster = orderMaster;
    }
    public Producto getProduct() {
        return this.product;
    }
    
    public void setProduct(Producto product) {
        this.product = product;
    }
    public Float getOrderdetailquantity() {
        return this.orderdetailquantity;
    }
    
    public void setOrderdetailquantity(Float orderdetailquantity) {
        this.orderdetailquantity = orderdetailquantity;
    }
    public Float getOrderdetailtotal() {
        return this.orderdetailtotal;
    }
    
    public void setOrderdetailtotal(Float orderdetailtotal) {
        this.orderdetailtotal = orderdetailtotal;
    }
    public Float getOrderdetailunitprice() {
        return this.orderdetailunitprice;
    }
    
    public void setOrderdetailunitprice(Float orderdetailunitprice) {
        this.orderdetailunitprice = orderdetailunitprice;
    }
    public String getProductcolor() {
        return this.productcolor;
    }
    
    public void setProductcolor(String productcolor) {
        this.productcolor = productcolor;
    }




}


