package retail.modelo.entidades;
// Generated 02-18-2019 03:12:08 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * OrderType generated by hbm2java
 */
public class OrderType  implements java.io.Serializable {


     private int typeid;
     private String typename;
     private Integer typestate;
     private Set orderMasters = new HashSet(0);

    public OrderType() {
    }

    public OrderType(String typename, Integer typestate, Set orderMasters) {
       this.typename = typename;
       this.typestate = typestate;
       this.orderMasters = orderMasters;
    }
   
    public int getTypeid() {
        return this.typeid;
    }
    
    public void setTypeid(int typeid) {
        this.typeid = typeid;
    }
    public String getTypename() {
        return this.typename;
    }
    
    public void setTypename(String typename) {
        this.typename = typename;
    }
    public Integer getTypestate() {
        return this.typestate;
    }
    
    public void setTypestate(Integer typestate) {
        this.typestate = typestate;
    }
    public Set getOrderMasters() {
        return this.orderMasters;
    }
    
    public void setOrderMasters(Set orderMasters) {
        this.orderMasters = orderMasters;
    }




}


