package retail.modelo.entidades;
// Generated 02-18-2019 03:12:08 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Provider generated by hbm2java
 */
public class Provider  implements java.io.Serializable {


     private int providerid;
     private String providername;
     private int providerstate;
     private Contact contact;
     private Set orderMasters = new HashSet(0);

    public Provider() {
    }

	
    public Provider(int providerid, int providerstate, Contact contacid) {
        this.providerid = providerid;
        this.providerstate = providerstate;
        this.contact = contacid;
    }
    public Provider(int providerid, String providername, int providerstate, Contact contacid, Set orderMasters) {
       this.providerid = providerid;
       this.providername = providername;
       this.providerstate = providerstate;
       this.contact = contacid;
       this.orderMasters = orderMasters;
    }
   
    public int getProviderid() {
        return this.providerid;
    }
    
    public void setProviderid(int providerid) {
        this.providerid = providerid;
    }
    public String getProvidername() {
        return this.providername;
    }
    
    public void setProvidername(String providername) {
        this.providername = providername;
    }
    public int getProviderstate() {
        return this.providerstate;
    }
    
    public void setProviderstate(int providerstate) {
        this.providerstate = providerstate;
    }
    public Contact getContact() {
        return this.contact;
    }
    
    public void setContact(Contact contacid) {
        this.contact = contacid;
    }
    public Set getOrderMasters() {
        return this.orderMasters;
    }
    
    public void setOrderMasters(Set orderMasters) {
        this.orderMasters = orderMasters;
    }




}


