package retail.modelo.entidades;
// Generated 02-18-2019 03:12:08 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Vendedor generated by hbm2java
 */
public class Vendedor  implements java.io.Serializable {


     private int idVendedor;
     private String nombreVendedor;
     private String apellidoVendedor;
     private String direccionVendedor;
     private char sexoVendedor;
     private String telefonoVendedor;
     private String duiVendedor;
     private Set ventases = new HashSet(0);
     private Set orderMasters = new HashSet(0);

    public Vendedor() {
    }

	
    public Vendedor(int idVendedor, String nombreVendedor, String apellidoVendedor, String direccionVendedor, char sexoVendedor, String telefonoVendedor, String duiVendedor) {
        this.idVendedor = idVendedor;
        this.nombreVendedor = nombreVendedor;
        this.apellidoVendedor = apellidoVendedor;
        this.direccionVendedor = direccionVendedor;
        this.sexoVendedor = sexoVendedor;
        this.telefonoVendedor = telefonoVendedor;
        this.duiVendedor = duiVendedor;
    }
    public Vendedor(int idVendedor, String nombreVendedor, String apellidoVendedor, String direccionVendedor, char sexoVendedor, String telefonoVendedor, String duiVendedor, Set ventases, Set orderMasters) {
       this.idVendedor = idVendedor;
       this.nombreVendedor = nombreVendedor;
       this.apellidoVendedor = apellidoVendedor;
       this.direccionVendedor = direccionVendedor;
       this.sexoVendedor = sexoVendedor;
       this.telefonoVendedor = telefonoVendedor;
       this.duiVendedor = duiVendedor;
       this.ventases = ventases;
       this.orderMasters = orderMasters;
    }
   
    public int getIdVendedor() {
        return this.idVendedor;
    }
    
    public void setIdVendedor(int idVendedor) {
        this.idVendedor = idVendedor;
    }
    public String getNombreVendedor() {
        return this.nombreVendedor;
    }
    
    public void setNombreVendedor(String nombreVendedor) {
        this.nombreVendedor = nombreVendedor;
    }
    public String getApellidoVendedor() {
        return this.apellidoVendedor;
    }
    
    public void setApellidoVendedor(String apellidoVendedor) {
        this.apellidoVendedor = apellidoVendedor;
    }
    public String getDireccionVendedor() {
        return this.direccionVendedor;
    }
    
    public void setDireccionVendedor(String direccionVendedor) {
        this.direccionVendedor = direccionVendedor;
    }
    public char getSexoVendedor() {
        return this.sexoVendedor;
    }
    
    public void setSexoVendedor(char sexoVendedor) {
        this.sexoVendedor = sexoVendedor;
    }
    public String getTelefonoVendedor() {
        return this.telefonoVendedor;
    }
    
    public void setTelefonoVendedor(String telefonoVendedor) {
        this.telefonoVendedor = telefonoVendedor;
    }
    public String getDuiVendedor() {
        return this.duiVendedor;
    }
    
    public void setDuiVendedor(String duiVendedor) {
        this.duiVendedor = duiVendedor;
    }
    public Set getVentases() {
        return this.ventases;
    }
    
    public void setVentases(Set ventases) {
        this.ventases = ventases;
    }
    public Set getOrderMasters() {
        return this.orderMasters;
    }
    
    public void setOrderMasters(Set orderMasters) {
        this.orderMasters = orderMasters;
    }




}


