package retail.modelo.entidades;
// Generated 02-18-2019 03:12:08 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ventas generated by hbm2java
 */
public class Ventas  implements java.io.Serializable {


     private int idVenta;
     private Clientes clientes;
     private Vendedor vendedor;
     private Date fechaVenta;
     private double totalVenta;
     private int estado;
     private Set detalleventas = new HashSet(0);

    public Ventas() {
    }

	
    public Ventas(int idVenta, Clientes clientes, Vendedor vendedor, Date fechaVenta, double totalVenta, int estado) {
        this.idVenta = idVenta;
        this.clientes = clientes;
        this.vendedor = vendedor;
        this.fechaVenta = fechaVenta;
        this.totalVenta = totalVenta;
        this.estado = estado;
    }
    public Ventas(int idVenta, Clientes clientes, Vendedor vendedor, Date fechaVenta, double totalVenta, int estado, Set detalleventas) {
       this.idVenta = idVenta;
       this.clientes = clientes;
       this.vendedor = vendedor;
       this.fechaVenta = fechaVenta;
       this.totalVenta = totalVenta;
       this.estado = estado;
       this.detalleventas = detalleventas;
    }
   
    public int getIdVenta() {
        return this.idVenta;
    }
    
    public void setIdVenta(int idVenta) {
        this.idVenta = idVenta;
    }
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }
    public Vendedor getVendedor() {
        return this.vendedor;
    }
    
    public void setVendedor(Vendedor vendedor) {
        this.vendedor = vendedor;
    }
    public Date getFechaVenta() {
        return this.fechaVenta;
    }
    
    public void setFechaVenta(Date fechaVenta) {
        this.fechaVenta = fechaVenta;
    }
    public double getTotalVenta() {
        return this.totalVenta;
    }
    
    public void setTotalVenta(double totalVenta) {
        this.totalVenta = totalVenta;
    }
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }
    public Set getDetalleventas() {
        return this.detalleventas;
    }
    
    public void setDetalleventas(Set detalleventas) {
        this.detalleventas = detalleventas;
    }




}


